### PR TITLE
Plan Monitoring Integration

### PR DESCRIPTION
**Pull request by franklinselva**
This PR integrates plan monitoring using dependency graphs for the available plan dispatcher. 

The idea currently implements two mirrors of the same dependency graph generated from the plan: one is provided with executable context primarily supporting the execution and the other provides a status of all nodes in the graph. I think it should help with easier extension of monitoring services to rich command line interfaces and other similar purposes.

### CODE REVIEW

**Review by alexander-sung — APPROVED** [review]
Sorry, I have little time to look into the details. Overall, I'm glad to have this branch merged, therefore nothing against it. Is there anything specific I should test? I assume @sebastianstock will have a closer look.

**Comment by alexander-sung** [comment]
There is one more thing to add: When executing the `robot_example.py`, I get a **randomly** occurring AssertionError.
```
**********
* Plan *
(Fraction(0, 1), survey(area, base_station), Fraction(10, 1))
(Fraction(1, 5), survey(area, base_station), Fraction(10, 1))
(Fraction(101, 10), send_info, Fraction(0, 1))
(Fraction(51, 5), acquire_plates_order, Fraction(0, 1))
(Fraction(103, 10), move(base_station, l1), Fraction(1, 1))
(Fraction(57, 5), inspect_plate(l1), Fraction(2, 1))
(Fraction(23, 2), move(l1, l3), Fraction(1, 1))
(Fraction(63, 5), inspect_plate(l3), Fraction(2, 1))
(Fraction(127, 10), move(l3, l4), Fraction(1, 1))
(Fraction(69, 5), inspect_plate(l4), Fraction(2, 1))
(Fraction(139, 10), move(l4, l2), Fraction(1, 1))
(Fraction(15, 1), inspect_plate(l2), Fraction(2, 1))
(Fraction(151, 10), move(l2, charging_station), Fraction(1, 1))
**********
Surveying area Area(area) from location Location(base_station)
Traceback (most recent call last):
  File "/home/alsu01/up_ws/src/embedded-systems-bridge/examples/robot_example.py", line 246, in <module>
    main()
  File "/home/alsu01/up_ws/src/embedded-systems-bridge/examples/robot_example.py", line 237, in main
    dispatcher.execute_plan(plan, graph_executor)
  File "/home/alsu01/up_ws/src/embedded-systems-bridge/up_esb/plexmo/dispatcher.py", line 131, in execute_plan
    self._monitor.process_action_result(result, dry_run=options.get("dry_run", True))
  File "/home/alsu01/up_ws/src/embedded-systems-bridge/up_esb/plexmo/monitor.py", line 105, in process_action_result
    exception = process_action_result(result)
  File "/home/alsu01/up_ws/src/embedded-systems-bridge/up_esb/exceptions.py", line 93, in process_action_result
    assert result.precondition_status == ConditionStatus.SUCCEEDED
AssertionError
```
Executing the same script, no changes, can also succeed. The plan is slightly different then.
```
**********
* Plan *
(Fraction(0, 1), survey(area, base_station), Fraction(10, 1))
(Fraction(101, 10), send_info, Fraction(0, 1))
(Fraction(51, 5), acquire_plates_order, Fraction(0, 1))
(Fraction(103, 10), move(base_station, l3), Fraction(1, 1))
(Fraction(57, 5), inspect_plate(l3), Fraction(2, 1))
(Fraction(23, 2), move(l3, l1), Fraction(1, 1))
(Fraction(63, 5), inspect_plate(l1), Fraction(2, 1))
(Fraction(127, 10), move(l1, l2), Fraction(1, 1))
(Fraction(69, 5), inspect_plate(l2), Fraction(2, 1))
(Fraction(139, 10), move(l2, l4), Fraction(1, 1))
(Fraction(15, 1), inspect_plate(l4), Fraction(2, 1))
(Fraction(151, 10), move(l4, charging_station), Fraction(1, 1))
**********
Surveying area Area(area) from location Location(base_station)
Sending information to the base station
Acquiring plates order
Moving from Location(base_station) to Location(l3)
Inspecting plate at location Location(l3)
Moving from Location(l3) to Location(l1)
Inspecting plate at location Location(l1)
Moving from Location(l1) to Location(l2)
Inspecting plate at location Location(l2)
Moving from Location(l2) to Location(l4)
Inspecting plate at location Location(l4)
Moving from Location(l4) to Location(charging_station)
**********
MonitorStatus.FINISHED
DispatcherStatus.FINISHED
**********
```

**Comment by franklinselva** [comment]
> There is one more thing to add: When executing the `robot_example.py`, I get a **randomly** occurring AssertionError.
> 
> ```
> **********
> * Plan *
> (Fraction(0, 1), survey(area, base_station), Fraction(10, 1))
> (Fraction(1, 5), survey(area, base_station), Fraction(10, 1))
> (Fraction(101, 10), send_info, Fraction(0, 1))
> (Fraction(51, 5), acquire_plates_order, Fraction(0, 1))
> (Fraction(103, 10), move(base_station, l1), Fraction(1, 1))
> (Fraction(57, 5), inspect_plate(l1), Fraction(2, 1))
> (Fraction(23, 2), move(l1, l3), Fraction(1, 1))
> (Fraction(63, 5), inspect_plate(l3), Fraction(2, 1))
> (Fraction(127, 10), move(l3, l4), Fraction(1, 1))
> (Fraction(69, 5), inspect_plate(l4), Fraction(2, 1))
> (Fraction(139, 10), move(l4, l2), Fraction(1, 1))
> (Fraction(15, 1), inspect_plate(l2), Fraction(2, 1))
> (Fraction(151, 10), move(l2, charging_station), Fraction(1, 1))
> **********
> Surveying area Area(area) from location Location(base_station)
> Traceback (most recent call last):
>   File "/home/alsu01/up_ws/src/embedded-systems-bridge/examples/robot_example.py", line 246, in <module>
>     main()
>   File "/home/alsu01/up_ws/src/embedded-systems-bridge/examples/robot_example.py", line 237, in main
>     dispatcher.execute_plan(plan, graph_executor)
>   File "/home/alsu01/up_ws/src/embedded-systems-bridge/up_esb/plexmo/dispatcher.py", line 131, in execute_plan
>     self._monitor.process_action_result(result, dry_run=options.get("dry_run", True))
>   File "/home/alsu01/up_ws/src/embedded-systems-bridge/up_esb/plexmo/monitor.py", line 105, in process_action_result
>     exception = process_action_result(result)
>   File "/home/alsu01/up_ws/src/embedded-systems-bridge/up_esb/exceptions.py", line 93, in process_action_result
>     assert result.precondition_status == ConditionStatus.SUCCEEDED
> AssertionError
> ```

@alexander-sung Sorry for the delay.

The assertion error occurs due to a failed precondition in the first plan. The first plan seems to be invalid at the moment since a single robot cannot execute the survey action twice given the start time. Do you think we should add a step to validate the plan before execution?

**Comment by alexander-sung** [comment]
What delay? No problem, it wasn't urgent from my side.

I don't think I'm the one to decide how to handle it. First, is the randomness intentional? Can it be addressed? Or is the reasoning here that different plans could be (randomly) returned as long as they are valid?

Error and crash give the impression that something happened which should not occur at all. So, if you want to keep the possibility of the invalid plan, I suggest a validation before executing each **action**. If the time constraint cannot be fulfilled, print out the error and abort action/plan execution. My assumption here is that a complete **plan** validation beforehand is redundant to planning in the first place - why not produce a valid plan directly then? As long as there are program crashes, I see a necessity to act - either by avoiding the situation entirely, or by resolving the error gracefully.

**Comment by franklinselva** [comment]
Yes, the randomness is intentional. I think the issue in creating a valid plan directly is due to the way the problem is defined. I will take a look into it.

However, since the refactored version doesn't fully support checking time constraints yet (planned in the next PR focusing on the parallel actions and time-triggered actions), I would hold on to these additions separately. 

And I agree with the way the exceptions are handled currently. I think it is better to handle it now before moving forward.

**Review by sebastianstock — APPROVED** [review]
Looks good to me. Very nice.

**Pull request merged**
