### PR TITLE
Minor Fixes to the Bridge

### PR DESCRIPTION
**Pull request by franklinselva**
This PR addresses the expected minor changes to the bridge interface and examples.

Expected changes include,
     - `set_initial_values()` accepts initial_values as an argument to add initial values as default. The method doesn't depend on API functions to set the initial default value

### CODE REVIEW

**Comment by franklinselva** [comment]
Closes #3

**Comment by franklinselva** [comment]
@alexander-sung The changes are ready for review.

**Comment by alexander-sung** [comment]
This doesn't seem to be minor fixes to me. It's a big pull request with changes to the interface. I don't like introducing `Any` to the bridge if it can be avoided. Is there need? I need to investigate in detail. Indeed it seems you listed all the intended changes in the description.

**Comment by franklinselva** [comment]
Indeed. Initially, it was planned to be minor fixes that I could notice during the paperwork. I can go over the description of the missing issues that are not linked to the PR ATM.

**Review by alexander-sung — CHANGES_REQUESTED** [review]
I applied the fixes to execution and the interface change on bridge.solve() separately. We should discuss the remaining parts in detail.

**Comment by franklinselva** [comment]
Thanks. I went through your changes. 

This pull request remains with two changes. 

 - The example scripts are updated to use bridge functionalities.
 - The work on `set_initial_values()` is also a part of this PR. If needed, I can move the changes related to `set_initial_values()` to a separate pull request.

**Pull request closed without merging**
