### PR TITLE
Add more description and references to the README

### PR DESCRIPTION
**Pull request by alexander-sung**
Hello to you. We should have some more description on this repository, even though it probably isn't an entrypoint to our work, so here is a proposal. Anything you want to add? Please do. We should also add the paper reference once available.

### CODE REVIEW

**Review by sebastianstock — APPROVED** [review]
Thanks for pushing this forward @alexander-sung !

We could mention that it can be easily installed via pip. But I just tried installing it in an empty environment and it did not work when it tried resolving dependencies on up and up-aries. We can wait for the 1.0 release of UP, today, and resolve it afterwards.

**Comment by franklinselva** [comment]
I have added the installation instructions using pip but didn't add a pip badge yet. Do we need it now? 

 It is strange that I didn't encounter the dependency conflict when using PyPi. We could remove the instructions if we couldn't install `up-esb` through PyPi

**Comment by alexander-sung** [comment]
Thanks you two for your feedback. We can check the UP release and continue next week but pip, yes or no, I would continue with the other description independently from that and add a recommendation to pip when it's clarified. Well, hopefully it is clarified next week.

**Review by franklinselva — APPROVED** [review]

**Comment by alexander-sung** [comment]
Thanks for the additions. 👍

**Pull request merged**
