### PR TITLE
Adapt to changes of UP's SequentialSimulator

### PR DESCRIPTION
**Pull request by sebastianstock**
The simulator in UP has changed recently. It has been renamed to UPSequentialSimulator and also its interface has been changed. 
This PR adapts the monitor to those changes.

### CODE REVIEW

**Comment by alexander-sung** [comment]
Which UP changes is this referring to? Even after explicitly updating UP, the changes in this pull request fail for me because Python `cannot import name 'UPSequentialSimulator' from 'unified_planning.engines'`. I'm using UP release versions from pip. Are you installing from source?

**Comment by sebastianstock** [comment]
The change is from this commit: https://github.com/aiplan4eu/unified-planning/commit/84bb82c9257a5047be6d67410072ff8a2e0395bf
I don't know which version this commit was related to, but currently I have installed version 0.5.0.438.dev1

**Comment by mikand** [comment]
@alexander-sung We need to make a release. You should be able to install a recent enough version with `pip install --pre unified-planning` @alvalentini FYK

**Comment by alexander-sung** [comment]
Yes, indeed. `pip install --pre unified-planning` even installed the newer 0.5.0.441.dev1 version, that's fine. I installed version 0.5.0.438.dev1 explicitly before, also no problem.

**Pull request merged**
