### PR TITLE
Fix examples for esb

### PR DESCRIPTION
**Pull request by franklinselva**
In this PR, the examples for using `up_esb` has been refactored.

### CODE REVIEW

**Comment by alexander-sung** [comment]
I review this pull request first now, does it make sense?

**Comment by franklinselva** [comment]
Yes. This PR only focuses on the examples for now.

**Comment by franklinselva** [comment]
@alexander-sung I still have a concern about the parallel execution example thinking it is not producing a solid plan. What are your thoughts on this?

**Comment by alexander-sung** [comment]
Some more minor things. I'm wondering if you get different pylint results than me, so hopefully the changes are fine for you as well.

Other than that, all examples run nicely, and they also look nicer this way. Many thanks.

**Review by alexander-sung — APPROVED** [review]

**Comment by alexander-sung** [comment]
> @alexander-sung I still have a concern about the parallel execution example thinking it is not producing a solid plan. What are your thoughts on this?

Oh, I missed your question in between. "solid" plan? I didn't notice it failing, though, and will have another look.

**Comment by alexander-sung** [comment]
```
**********
* Plan *
(Fraction(0, 1), Survey(area), Fraction(5, 1))
(Fraction(1, 5), Survey(area), Fraction(5, 1))
(Fraction(3, 10), Survey(area), Fraction(5, 1))
(Fraction(2, 5), Survey(area), Fraction(5, 1))
(Fraction(51, 10), SendInfo(l1), Fraction(0, 1))
(Fraction(51, 10), SendInfo(l4), Fraction(0, 1))
(Fraction(11, 2), SendInfo(l3), Fraction(0, 1))
(Fraction(28, 5), Move(l1, l3), Fraction(5, 1))
(Fraction(28, 5), SendInfo(l2), Fraction(0, 1))
(Fraction(107, 10), Move(l3, l2), Fraction(5, 1))
(Fraction(79, 5), Move(l2, l4), Fraction(5, 1))
**********
Surveying area Area-0-10-0-10
Surveying area Area-0-10-0-10
Surveying area Area-0-10-0-10
Sending info about l1
Sending info about l4
Sending info about l1
Sending info about l4
Moving from l1 to l3
Sending info about l2
Moving from l1 to l3
Sending info about l2
Moving from l3 to l2
Moving from l2 to l4
```
This is the output when running `parallel.py`. Are we talking about the same thing? Actually, the plan looks solid to me but indeed the execution seems to be off. Most info is sent twice, I3 is not sent at all, one surveying is missing, and of course parallel execution is hard to validate in this example. On the other hand, the plan itself should be alright.

**Comment by franklinselva** [comment]
Yes. The execution can be fixed on the other pull request where we will be reworking on parallel execution. So should we rewrite the example now since this will be the only script that produces an unexpected result?

**Comment by alexander-sung** [comment]
No, I think it's fine with the fix on parallel execution upcoming, thus suggest to proceed with merging and the next pull request. 👍

**Pull request merged**
